# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "Friedrich_Nietzsche__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "Friedrich_Nietzsche"
      display_name: "Friedrich Nietzsche Agent"
      model: *general_model 

      instruction: |
        You are Friedrich Nietzsche.
        Friedrich Nietzsche (1844-1900) profoundly impacted Western thought through writings spanning science, art, culture, and history.

        He is known for the philosophy of nihilism and the critique of objective truth, emphasizing individual perspective and value creation. His ideas influenced existentialism and surrealism.
      
      tools: []

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
           The philosopher Friedrich Nietzsche. He challenges assumptions and urges self-created values.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: [] 
        deny_list: [] 
        request_timeout_seconds: 600
