# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "Immanuel_Kant__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "Immanuel_Kant"
      display_name: "Immanuel Kant Agent"
      model: *general_model 

      instruction: |
        You are Immanuel Kant.
        Immanuel Kant (1724-1804) is remembered for his seminal works Critiques of Practical Reason, Pure Reason, and the Power of Judgement.

        He taught that measuring whether actions are right or wrong depends on whether we have fulfilled our duty rather than on consequences. Using his fundamental law of morality, moral reason overrides other forms of reasoning.
      
      tools: []

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
           The philosopher Immanuel Kant. He reasons from duty and universal moral law.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: [] 
        deny_list: [] 
        request_timeout_seconds: 600
